// <auto-generated />
using System;
using K1Y25_BE02_HuynhVinhHung_BT2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace K1Y25_BE02_HuynhVinhHung_BT2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("K1Y25_BE02_HuynhVinhHung_BT2.Models.AllowAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessProperties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AllowAccesses");
                });

            modelBuilder.Entity("K1Y25_BE02_HuynhVinhHung_BT2.Models.Intern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CitizenIdentification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CitizenIdentificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cvfile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EntranceTest")
                        .HasColumnType("real");

                    b.Property<string>("ForeignLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FullTime")
                        .HasColumnType("boolean");

                    b.Property<bool>("HiddenToEnterprise")
                        .HasColumnType("boolean");

                    b.Property<string>("HowToKnowAlta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("InternAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("InternEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("InternMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InternMailReplace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InternName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InternPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InternSpecialized")
                        .HasColumnType("integer");

                    b.Property<string>("InternStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Internable")
                        .HasColumnType("boolean");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobFields")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkProduct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PasswordStatus")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReadyToWork")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TelephoneNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("YearOfExperiences")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Interns");
                });

            modelBuilder.Entity("K1Y25_BE02_HuynhVinhHung_BT2.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("K1Y25_BE02_HuynhVinhHung_BT2.Models.User", b =>
                {
                    b.Property<int?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("UserId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("K1Y25_BE02_HuynhVinhHung_BT2.Models.AllowAccess", b =>
                {
                    b.HasOne("K1Y25_BE02_HuynhVinhHung_BT2.Models.Role", "Role")
                        .WithMany("AllowAccesses")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("K1Y25_BE02_HuynhVinhHung_BT2.Models.User", b =>
                {
                    b.HasOne("K1Y25_BE02_HuynhVinhHung_BT2.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("K1Y25_BE02_HuynhVinhHung_BT2.Models.Role", b =>
                {
                    b.Navigation("AllowAccesses");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
